name: BetterSleep
version: ${project.version}

author: Lavariator

main: betterSleep.Main

commands:
  bettersleep:
    usage: /<command> [pct/mode] [<percentage>/<percentage/playercount>]

permissions:
  bettersleep.config:
    description: Lets user to change the plugin's settings
    default: op
